version: '3'

volumes:
  postgres_volume:

services:
  storage:
    image: postgres:16.1
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - deploy/env/.env.prod
    expose:
      - ${PG_PORT}
    command: -p ${PG_PORT}

  migrator:
    build:
      context: .
      dockerfile: deploy/dockerfiles/migrator.Dockerfile
    env_file:
      - deploy/env/.env.prod
    depends_on:
      - storage
    environment:
      PG_HOST: storage

  redis:
    image: redis:7.2.4
    restart: always
    env_file:
      - deploy/env/.env.prod
    expose:
      - ${REDIS_PORT}
    command: --port ${REDIS_PORT}

  auth_service:
    build:
      context: .
      dockerfile: deploy/dockerfiles/auth.Dockerfile
    env_file:
      - deploy/env/.env.prod
    depends_on:
      - storage
      - white_list
    environment:
      PG_HOST: storage
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${SWAGGER_PORT}:${SWAGGER_PORT}"
    restart: on-failure