version: '3'

volumes:
  postgres_volume:

name: "auth_app_prod"

services:
  storage:
    image: postgres:16.1
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - env/.env.prod
    ports:
      - "${PG_PORT}:${PG_PORT}"
    command: -p ${PG_PORT}